### ISSUE TITLE
Cannot Init Usb Cam Hardware

### ISSUE THREAD

**Issue by joewong00** [yoshito-n-students/usb_cam_hardware#2]
Hi,

I used compressed packet controller for 4 usb cam, however one of them will give me this error:

: Cannot start streaming
: Cannot init usb cam hardware

I tried interchanging the usb cam groups in the launch file, all the cameras work fine, but only a maximum of 3 groups are working fine. May I know what are the possible problems here?

**Comment by yoshito-okada** [comment]
Maybe the power supply or data transfer capability of your computer is not sufficient for 4 cameras. Requesting lower image resolutions to cameras may improve if the issue is the transfer capability.

**Comment by joewong00** [comment]
Yes, I realised that it was the data transfer problem, is too power heavy for many cameras with high resolution and framerate. It is fixed when I lowered them, thanks!
